{% set name = "pyodbc" %}
{% set version = "4.0.24" %}
{% set sha256 = "4326abb737dec36156998d52324921673d30f575e1e0998f0c5edd7de20e61d4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - setup.patch  # [unix]

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - unixodbc   # [unix]
  run:
    - python

test:
  imports:
    - pyodbc

about:
  home: https://github.com/mkleehammer/pyodbc
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'DB API Module for ODBC'
  description: |
    pyodbc is a Python DB API 2 module for ODBC. This project provides an
    up-to-date, convenient interface to ODBC using native data types like
    datetime and decimal.
  doc_url: http://mkleehammer.github.io/pyodbc/
  doc_source_url: https://github.com/mkleehammer/pyodbc/blob/master/docs/index.md
  dev_url: https://github.com/mkleehammer/pyodbc

extra:
  recipe-maintainers:
    - nehaljwani
