travis:
  secure:
    BINSTAR_TOKEN: T8p2MEwuTxQo1JFOAsgfyVeDyD+1hl4m5pBb8TXaJqMpX1YMf8uzpHa7I6CVlVjtKgLVcupNpNX00TCNuDHC9GsRrKhTxvmCN4VUVrXBVorfCUCdr7/rClMyM4uf1P9VedXmnxMBIw8q3ufiytPcmDMoIszFnAkE9fhGEtvMdtxf9wtmH3GMvJxgD6wTK3L5+f+sHNdiP7IFQqHAPH23tHzUb7cKRHOoc1pki92I+JnCFIDjdeDdzDc2UOBubUeWw++7H8yT4DibsnMS/8BXehU5YhnP1EO65BhpLwD6th+tj4qDWKFcWuVRLgIP/JABtpVHi8lHU4Td7uHHXAqsOA/dcUe0iJ1FMGS4KRIk8P2dBWEf1vPJ3JdElY34XO+L9YrNNGeAkxj+2WZIRAyNxe47DQgB2xHaGQOXZYojmTNxilZrucoFdFENC34xyTyzNDEh3BmfH5s+YlRIxQVaYKsTnVyKMN+ejFV0mg6EgAoRiNNY2AtLRU5vXDRa4f1u9fNJYrdlknHAzmEV1V+DdfQm2zDYIXsRafNvHgWWqTSJKDH7nMxSDIpsMiSlyxwT//7OOntP0h4AZ4cKGFhhB1+IlwkdxgfN3qChSd3Ofm7V97gPEK9ylugGMKOqcRx2+RHgAvs4GY8dTpqnK6nxs6cEk9FZffUWjIt9vaa+Wmw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
